version: '3.9'

services:
  db:
    image: postgres:16
    container_name: placas_db
    environment:
      POSTGRES_DB: placas
      POSTGRES_USER: placa
      POSTGRES_PASSWORD: placa
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U placa -d placas"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: placas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com.br
      PGADMIN_DEFAULT_PASSWORD: admin123456
    ports:
      - "8080:80"
    depends_on:
      - db

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: placas
      POSTGRES_USER: placa
      POSTGRES_PASSWORD: placa
      POSTGRES_HOST: db  
      POSTGRES_PORT: 5432
    volumes:
      - ./uploaded_images:/app/uploaded_images
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
