version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: placas
      POSTGRES_USER: placa
      POSTGRES_PASSWORD: placa
      POSTGRES_HOST: host.docker.internal # Or your DB service name if in compose
      POSTGRES_PORT: 5432
    volumes: # Add this section
      - ./uploaded_images:/app/uploaded_images # Maps host dir to container dir